/*
===============================================================================
 Project      : UrbanLease
 Module       : Notification Service
 Database     : urbanlease_notification
 Script       : V1__create_schema.sql
 
 Description:
 Creates the Notification database schema.
===============================================================================
*/
-- =============================================================================
-- Create Database
-- =============================================================================

CREATE DATABASE urbanlease_notification
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE urbanlease_notification;

-- =============================================================================
-- TABLE : notification_templates
-- Description :
-- Stores reusable notification templates.
-- =============================================================================

CREATE TABLE notification_templates
(
    -- Primary Key
    id BIGINT AUTO_INCREMENT,

    -- Public Identifier
    uuid CHAR(36) NOT NULL,

    -- Template Information
    template_code VARCHAR(100) NOT NULL,

    template_name VARCHAR(150) NOT NULL,

    notification_channel ENUM(
        'EMAIL',
        'SMS',
        'PUSH',
        'IN_APP'
    ) NOT NULL,

    subject VARCHAR(255),

    message_template TEXT NOT NULL,

    template_status ENUM(
        'ACTIVE',
        'INACTIVE'
    ) NOT NULL DEFAULT 'ACTIVE',

    description VARCHAR(255),

    -- Status
    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    -- Audit Columns
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    created_by VARCHAR(100),

    updated_by VARCHAR(100),

    -- Constraints
    CONSTRAINT pk_notification_templates
        PRIMARY KEY (id),

    CONSTRAINT uk_notification_templates_uuid
        UNIQUE (uuid),

    CONSTRAINT uk_notification_templates_code
        UNIQUE (template_code)

)
ENGINE = InnoDB
DEFAULT CHARSET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Stores reusable notification templates';

-- =============================================================================
-- TABLE : notifications
-- Description :
-- Stores notification requests generated by all services.
-- =============================================================================

CREATE TABLE notifications
(
    -- Primary Key
    id BIGINT AUTO_INCREMENT,

    -- Public Identifier
    uuid CHAR(36) NOT NULL,

    -- Cross-Service Reference
    recipient_uuid CHAR(36) NOT NULL,

    -- Internal Reference
    template_id BIGINT,

    -- Source Information
    source_service ENUM(
        'AUTH',
        'USER',
        'PROPERTY',
        'BOOKING',
        'PAYMENT',
        'MAINTENANCE',
        'DOCUMENT',
        'AI'
    ) NOT NULL,

    notification_channel ENUM(
        'EMAIL',
        'SMS',
        'PUSH',
        'IN_APP'
    ) NOT NULL,

    notification_type ENUM(
        'WELCOME',
        'OTP',
        'EMAIL_VERIFICATION',
        'PASSWORD_RESET',
        'BOOKING_CONFIRMATION',
        'BOOKING_CANCELLED',
        'PAYMENT_SUCCESS',
        'PAYMENT_FAILED',
        'RENT_REMINDER',
        'MAINTENANCE_CREATED',
        'MAINTENANCE_ASSIGNED',
        'MAINTENANCE_COMPLETED',
        'DOCUMENT_UPLOADED',
        'GENERAL'
    ) NOT NULL,

    recipient_address VARCHAR(255) NOT NULL,

    subject VARCHAR(255),

    message TEXT NOT NULL,

    delivery_status ENUM(
        'PENDING',
        'PROCESSING',
        'SENT',
        'DELIVERED',
        'FAILED',
        'READ'
    ) NOT NULL DEFAULT 'PENDING',

    scheduled_at DATETIME,

    sent_at DATETIME,

    delivered_at DATETIME,

    read_at DATETIME,

    failure_reason VARCHAR(500),

    retry_count INT NOT NULL DEFAULT 0,

    -- Status
    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    -- Audit Columns
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    created_by VARCHAR(100),

    updated_by VARCHAR(100),

    -- Constraints
    CONSTRAINT pk_notifications
        PRIMARY KEY (id),

    CONSTRAINT uk_notifications_uuid
        UNIQUE (uuid),

    CONSTRAINT fk_notifications_template_id
        FOREIGN KEY (template_id)
        REFERENCES notification_templates(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL

)
ENGINE = InnoDB
DEFAULT CHARSET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Stores notification requests';

-- =============================================================================
-- INDEXES
-- =============================================================================

CREATE INDEX idx_notification_templates_code
    ON notification_templates(template_code);

CREATE INDEX idx_notification_templates_channel
    ON notification_templates(notification_channel);

CREATE INDEX idx_notification_templates_status
    ON notification_templates(template_status);

CREATE INDEX idx_notification_templates_is_active
    ON notification_templates(is_active);

CREATE INDEX idx_notifications_recipient_uuid
    ON notifications(recipient_uuid);

CREATE INDEX idx_notifications_template_id
    ON notifications(template_id);

CREATE INDEX idx_notifications_source_service
    ON notifications(source_service);

CREATE INDEX idx_notifications_channel
    ON notifications(notification_channel);

CREATE INDEX idx_notifications_type
    ON notifications(notification_type);

CREATE INDEX idx_notifications_status
    ON notifications(delivery_status);

CREATE INDEX idx_notifications_scheduled_at
    ON notifications(scheduled_at);

CREATE INDEX idx_notifications_sent_at
    ON notifications(sent_at);

CREATE INDEX idx_notifications_is_active
    ON notifications(is_active);

-- =============================================================================
-- TABLE : notification_delivery_history
-- Description :
-- Stores every delivery attempt made by the Notification Service.
-- =============================================================================

CREATE TABLE notification_delivery_history
(
    -- Primary Key
    id BIGINT AUTO_INCREMENT,

    -- Public Identifier
    uuid CHAR(36) NOT NULL,

    -- Foreign Key
    notification_id BIGINT NOT NULL,

    -- Delivery Information
    delivery_attempt INT NOT NULL DEFAULT 1,

    provider_name ENUM(
        'SMTP',
        'TWILIO',
        'FIREBASE',
        'ONESIGNAL',
        'AWS_SES',
        'OTHER'
    ) NOT NULL,

    provider_reference VARCHAR(150),

    delivery_status ENUM(
        'PENDING',
        'PROCESSING',
        'SENT',
        'DELIVERED',
        'FAILED'
    ) NOT NULL,

    attempted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    response_message TEXT,

    failure_reason VARCHAR(500),

    -- Audit Columns
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    created_by VARCHAR(100),

    updated_by VARCHAR(100),

    -- Constraints
    CONSTRAINT pk_notification_delivery_history
        PRIMARY KEY (id),

    CONSTRAINT uk_notification_delivery_history_uuid
        UNIQUE (uuid),

    CONSTRAINT fk_notification_delivery_history_notification_id
        FOREIGN KEY (notification_id)
        REFERENCES notifications(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE

)
ENGINE = InnoDB
DEFAULT CHARSET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Stores notification delivery history';

-- =============================================================================
-- TABLE : notification_preferences
-- Description :
-- Stores user notification preferences.
-- =============================================================================

CREATE TABLE notification_preferences
(
    -- Primary Key
    id BIGINT AUTO_INCREMENT,

    -- Public Identifier
    uuid CHAR(36) NOT NULL,

    -- Cross-Service Reference
    user_uuid CHAR(36) NOT NULL,

    -- Channel Preferences
    email_enabled BOOLEAN NOT NULL DEFAULT TRUE,

    sms_enabled BOOLEAN NOT NULL DEFAULT TRUE,

    push_enabled BOOLEAN NOT NULL DEFAULT TRUE,

    in_app_enabled BOOLEAN NOT NULL DEFAULT TRUE,

    -- Notification Preferences
    booking_notifications BOOLEAN NOT NULL DEFAULT TRUE,

    payment_notifications BOOLEAN NOT NULL DEFAULT TRUE,

    maintenance_notifications BOOLEAN NOT NULL DEFAULT TRUE,

    marketing_notifications BOOLEAN NOT NULL DEFAULT FALSE,

    system_notifications BOOLEAN NOT NULL DEFAULT TRUE,

    -- Status
    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    -- Audit Columns
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    created_by VARCHAR(100),

    updated_by VARCHAR(100),

    -- Constraints
    CONSTRAINT pk_notification_preferences
        PRIMARY KEY (id),

    CONSTRAINT uk_notification_preferences_uuid
        UNIQUE (uuid),

    CONSTRAINT uk_notification_preferences_user_uuid
        UNIQUE (user_uuid)

)
ENGINE = InnoDB
DEFAULT CHARSET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Stores user notification preferences';

-- =============================================================================
-- INDEXES
-- =============================================================================

CREATE INDEX idx_notification_delivery_history_notification_id
    ON notification_delivery_history(notification_id);

CREATE INDEX idx_notification_delivery_history_provider
    ON notification_delivery_history(provider_name);

CREATE INDEX idx_notification_delivery_history_status
    ON notification_delivery_history(delivery_status);

CREATE INDEX idx_notification_delivery_history_attempted_at
    ON notification_delivery_history(attempted_at);

CREATE INDEX idx_notification_preferences_user_uuid
    ON notification_preferences(user_uuid);

CREATE INDEX idx_notification_preferences_is_active
    ON notification_preferences(is_active);
    

